/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1"
};


export default {
  Auth: {
    region: "us-west-1",
    userPoolId: "us-west-1_VhvACbvqC",
    userPoolWebClientId: "660bvluiuja8t7telpssm67e8f",
    // if identity pool used, also identityPoolId: "..."
  }
  // possibly other properties
};